# Crawling

Crawling of tweets for 10 nfts using snscrape

## Install and import required libraries

In [ ]:
!pip install snscrape

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting snscrape
  Downloading snscrape-0.5.0.20230113-py3-none-any.whl (69 kB)
     ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 69.2/69.2 KB 2.0 MB/s eta 0:00:00
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.8/dist-packages (from snscrape) (2.25.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.8/dist-packages (from snscrape) (3.9.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.8/dist-packages (from snscrape) (4.9.2)
Requirement already satisfied: pytz in /usr/local/lib/python3.8/dist-packages (from snscrape) (2022.7.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.8/dist-packages (from snscrape) (4.6.3)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->snscrape) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->snscrape) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->snscrape) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->snscrape) (1.24.3)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->snscrape) (1.7.1)
Installing collected packages: snscrape
Successfully installed snscrape-0.5.0.20230113

In [ ]:
import snscrape.modules.twitter as sntwitter
import pandas as pd

## NFTs

* Mutant Ape Yacht Club (MAYC)
* Azuki
* Bored Ape Yacht Club (BAYC)
* Meebits
* CryptoPunks
* CloneX
* The Potatoz
* Pixelmon
* MekaVerse
* Phanta Bear

In [ ]:
def to_csv(t_df, t_name): 
    t_df.to_csv(t_name, sep=',', index=False)

### Pixelmon

In [ ]:
pixel_query = ['pixelmon nft since:2023-01-01 until:2023-03-31 exclude:retweets exclude:replies',
              'pixelmon nft since:2022-10-01 until:2022-12-31 exclude:retweets exclude:replies',
              'pixelmon nft since:2022-07-01 until:2022-09-30 exclude:retweets exclude:replies',
              'pixelmon nft since:2022-04-01 until:2022-06-30 exclude:retweets exclude:replies',
              'pixelmon nft since:2022-01-01 until:2022-03-31 exclude:retweets exclude:replies'
              ]
          
t_max = 500
t_list = []
for query in pixel_query:
  for i,tweet in enumerate(sntwitter.TwitterSearchScraper(query).get_items()):
          if i>t_max:
              break
          t_list.append([tweet.date, tweet.id, tweet.rawContent, tweet.user.username, tweet.replyCount, tweet.retweetCount ,tweet.likeCount])

pixel_df = pd.DataFrame(t_list, columns=['Datetime', 'Tweet Id', 'Text', 'Username', 'Replies', 'Retweets', 'Likes'])
to_csv(pixel_df, 'pixel_tweets.csv')

pixel_df

,Datetime,Tweet Id,Text,Username,Replies,Retweets,Likes
0,2023-02-17 00:03:24+00:00,1626371698286272512,@Pixelmon @RetroHunters @yrn1ck :),Davion_NFT,0,0,0
1,2023-02-17 00:00:10+00:00,1626370887384547328,"Cautionary Tales From Hyped NFTs: Pixelmon, Ha...",Nftcryptoinfo,1,0,5
2,2023-02-16 22:03:32+00:00,1626341536148631552,üê≥10 Pixelmon - Generation 1 bought for Œû3.5\n\...,NFTEye_Alpha,0,0,2
3,2023-02-16 20:50:24+00:00,1626323131685011458,"üí∞Top 5 sales (last 30 min):\n1. Art Blocks, 1 ...",senorbotNFT,0,0,0
4,2023-02-16 17:00:41+00:00,1626265318698938369,"üê≥ Top Whale salesüîª (last 4h):\n1. Otherdeed, 7...",senorbotNFT,0,0,0
...,...,...,...,...,...,...,...
2500,2022-03-10 15:35:16+00:00,1501944787834130433,"Pixelmon hoped to be the Pokemon of NFT games,...",CautreelsJurgen,0,0,3
2501,2022-03-10 15:23:41+00:00,1501941873316794368,@tunaayd6666 @Astrals_NFT @Vidi_Art @drippieve...,0x_shake,0,0,0
2502,2022-03-10 14:54:22+00:00,1501934495481491461,@Maverick__23 @CyberBrokers_ Neither did they ...,milestones_nft,1,0,2
2503,2022-03-10 11:39:13+00:00,1501885383419699204,"Pixelmon, Squiggles, Hypebear, Gooniez, etc, s...",MayankBeed,4,2,10
2504,2022-03-10 07:53:55+00:00,1501828683044110336,@NFT_Shady @Riiwer1 @chrisGkHood @damian_demed...,s_stiefelmeyer,0,0,0

### MekaVerse

In [ ]:
meka_query = ['mekaverse nft since:2023-01-01 until:2023-03-31 exclude:retweets exclude:replies',
              'mekaverse nft since:2022-10-01 until:2022-12-31 exclude:retweets exclude:replies',
              'mekaverse nft since:2022-07-01 until:2022-09-30 exclude:retweets exclude:replies',
              'mekaverse nft since:2022-04-01 until:2022-06-30 exclude:retweets exclude:replies',
              'mekaverse nft since:2022-01-01 until:2022-03-31 exclude:retweets exclude:replies',
              'mekaverse nft since:2021-10-01 until:2021-12-31 exclude:retweets exclude:replies'
              ]
          
t_max = 417
t_list = []
for query in meka_query:
  for i,tweet in enumerate(sntwitter.TwitterSearchScraper(query).get_items()):
          if i>t_max:
              break
          t_list.append([tweet.date, tweet.id, tweet.rawContent, tweet.user.username, tweet.replyCount, tweet.retweetCount ,tweet.likeCount])

meka_df = pd.DataFrame(t_list, columns=['Datetime', 'Tweet Id', 'Text', 'Username', 'Replies', 'Retweets', 'Likes'])
to_csv(meka_df, 'meka_tweets.csv')

meka_df

,Datetime,Tweet Id,Text,Username,Replies,Retweets,Likes
0,2023-02-13 14:49:47+00:00,1625145214904987649,üî• Floor is Lava!!\n2 Mekas bought for 0.815 ET...,botMeka,0,0,0
1,2023-02-13 09:05:00+00:00,1625058445941518339,I bought this Mekaverse NFT for 8 ETH.\n\nAsk ...,Soy_Shills,1,4,4
2,2023-02-12 17:28:50+00:00,1624822854352089088,ü§ñ MekaBot #6200 bought for 0.035 ETH ($54)\nüéØ ...,botMeka,0,0,3
3,2023-02-12 12:29:41+00:00,1624747567878705157,MekaVerse - Floor price candlestick\nLast 100...,the_artist_nft,1,0,2
4,2023-02-12 03:04:12+00:00,1624605258562383875,multiple reports of a #UFO in the sky .The OG ...,NFTMasterpiece,0,1,4
...,...,...,...,...,...,...,...
2405,2021-12-04 12:26:46+00:00,1467108115493666820,Meka just listed under floor (-1.09 %)\n\nüí∞: 0...,nftflooralerts,0,0,1
2406,2021-12-04 12:13:47+00:00,1467104845626810369,Meka just listed under floor (-3.16 %)\n\nüí∞: 0...,nftflooralerts,3,0,7
2407,2021-12-04 11:42:49+00:00,1467097051347533824,Meka just listed under floor (-4.04 %)\n\nüí∞: 0...,nftflooralerts,0,0,1
2408,2021-12-04 11:33:46+00:00,1467094774352130050,GOOD MORNING NFT WORLD üåê‚òïÔ∏è‚òÄÔ∏è\nToday is a wonde...,MekaNFT,1,0,7
2409,2021-12-04 11:12:46+00:00,1467089492809027586,Meka just listed under floor (-1.09 %)\n\nüí∞: 0...,nftflooralerts,0,0,1

### Phanta Bear

In [ ]:
bear_query = ['phanta bear nft since:2023-01-01 until:2023-03-31 exclude:retweets exclude:replies',
              'phanta bear nft since:2022-10-01 until:2022-12-31 exclude:retweets exclude:replies',
              'phanta bear nft since:2022-07-01 until:2022-09-30 exclude:retweets exclude:replies',
              'phanta bear nft since:2022-04-01 until:2022-06-30 exclude:retweets exclude:replies',
              'phanta bear nft since:2022-01-01 until:2022-03-31 exclude:retweets exclude:replies'
              ]
          
t_max = 500
t_list = []
for query in bear_query:
  for i,tweet in enumerate(sntwitter.TwitterSearchScraper(query).get_items()):
          if i>t_max:
              break
          t_list.append([tweet.date, tweet.id, tweet.rawContent, tweet.user.username, tweet.replyCount, tweet.retweetCount ,tweet.likeCount])

bear_df = pd.DataFrame(t_list, columns=['Datetime', 'Tweet Id', 'Text', 'Username', 'Replies', 'Retweets', 'Likes'])
to_csv(bear_df, 'bear_tweets.csv')

bear_df

,Datetime,Tweet Id,Text,Username,Replies,Retweets,Likes
0,2023-02-13 14:05:21+00:00,1625134034421678084,2 Phanta Bear swept for a total of 0.66 ETH(97...,PhantaBearBots,0,0,0
1,2023-02-13 14:04:06+00:00,1625133715973349378,"Phanta Bear Top5 Sales within 24H [ 07:04, Feb...",PhantaBearBots,0,0,0
2,2023-02-13 09:41:33+00:00,1625067646176878592,PHANTA BEAR #8984 bought for 0.30 ETH (443.24 ...,PhantaBearBots,0,0,0
3,2023-02-13 05:56:04+00:00,1625010898728542208,PHANTA BEAR #6418 bought for 0.31 ETH (466.12 ...,PhantaBearBots,0,0,0
4,2023-02-13 05:56:00+00:00,1625010883180253184,"6 Phanta Bear swept for a total of 1.82 ETH(2,...",PhantaBearBots,0,0,0
...,...,...,...,...,...,...,...
1420,2022-01-10 08:39:55+00:00,1480459377328877570,ÂèóÂà∞ËèØË™ûÊ≠åÂ£áÂ§©ÁéãÂë®Êù∞ÂÄ´Âä†ÊåÅÁöÑ Phanta Bear #NFT È†ÖÁõÆÔºåËøëÊó•Â∏ÇÂ†¥ÁÜ±Â∫¶ÊåÅÁ∫åÂª∂Ááí„ÄÇ...,IoTrart,0,0,1
1421,2022-01-10 08:33:46+00:00,1480457826434621441,üê≥üê≥üê≥ NFT Whale Trade\n\n‚û°Ô∏èTransfer: [0x85ae29] ...,nftgobot,0,0,0
1422,2022-01-10 06:34:51+00:00,1480427903251009539,"According to Opensea data, the floor price of ...",Bitrisecapital_,0,0,1
1423,2022-01-10 06:31:09+00:00,1480426969065922560,Check out this item on OpenSea https://t.co/zO...,KingYou52325157,0,0,1
1424,2022-01-10 06:20:22+00:00,1480424257997848578,Phanta Bear NFTÔºåË∞Å‰ºöÊòØÊúÄÂêéÁöÑÊé•Áõò‰æ†Ôºü,loongBai,1,0,0

### Mutant Ape Yacht Club

In [ ]:
mayc_query = ['mutant ape yacht club nft since:2023-01-01 until:2023-03-31 exclude:retweets exclude:replies',
              'mutant ape yacht club nft since:2022-10-01 until:2022-12-31 exclude:retweets exclude:replies',
              'mutant ape yacht club nft since:2022-07-01 until:2022-09-30 exclude:retweets exclude:replies',
              'mutant ape yacht club nft since:2022-04-01 until:2022-06-30 exclude:retweets exclude:replies',
              'mutant ape yacht club nft since:2022-01-01 until:2022-03-31 exclude:retweets exclude:replies',
              'mutant ape yacht club nft since:2021-10-01 until:2021-12-31 exclude:retweets exclude:replies'
              ]
          
t_max = 417
t_list = []
for query in mayc_query:
  for i,tweet in enumerate(sntwitter.TwitterSearchScraper(query).get_items()):
          if i>t_max:
              break
          t_list.append([tweet.date, tweet.id, tweet.rawContent, tweet.user.username, tweet.replyCount, tweet.retweetCount ,tweet.likeCount])

mayc_df = pd.DataFrame(t_list, columns=['Datetime', 'Tweet Id', 'Text', 'Username', 'Replies', 'Retweets', 'Likes'])
to_csv(mayc_df, 'mayc_tweets.csv')

mayc_df

,Datetime,Tweet Id,Text,Username,Replies,Retweets,Likes
0,2023-02-17 06:45:29+00:00,1626472887111802880,üê≥1 Mutant Ape Yacht Club bought for Œû16.16\n\n...,NFTEye_Alpha,0,0,1
1,2023-02-17 06:39:17+00:00,1626471328013340674,üß™ Mutant Ape Yacht Club | #MAYC #NFT\n\n#12758...,NFT_Monitor,2,0,1
2,2023-02-17 06:31:25+00:00,1626469347123417088,üê≥1 Mutant Ape Yacht Club bought for Œû16.5\n\nüßπ...,NFTEye_Alpha,0,0,3
3,2023-02-17 06:30:24+00:00,1626469093376155649,üß™ Mutant Ape Yacht Club | #MAYC #NFT\n\n#12630...,NFT_Monitor,0,0,2
4,2023-02-17 06:29:24+00:00,1626468840178864131,üê≥4 Mutant Ape Yacht Club bought for Œû64.68\n\n...,NFTEye_Alpha,0,0,3
...,...,...,...,...,...,...,...
2503,2021-12-29 18:53:10+00:00,1476265050671390726,üìà #0x6E1 bought MutantApeYachtClub #25558 - Mu...,nft_bot_sniper,0,0,0
2504,2021-12-29 18:53:10+00:00,1476265050629459975,üìà #0x361 bought MutantApeYachtClub #5533 - Mut...,nft_bot_sniper,0,0,0
2505,2021-12-29 18:52:32+00:00,1476264890625052673,Mutant Ape Yacht Club | #MAYC\n\nID: #2512\nSo...,NFT_Monitor,0,0,0
2506,2021-12-29 18:51:36+00:00,1476264657551863811,üìà #0x60d bought MutantApeYachtClub #2512 - Mut...,nft_bot_sniper,1,0,0
2507,2021-12-29 18:49:25+00:00,1476264107452076033,Mutant Ape Yacht Club | #MAYC\n\nID: #13267\nS...,NFT_Monitor,0,0,0

### Azuki

In [ ]:
azuki_query = ['azuki nft since:2023-01-01 until:2023-03-31 exclude:retweets exclude:replies',
              'azuki nft since:2022-10-01 until:2022-12-31 exclude:retweets exclude:replies',
              'azuki nft since:2022-07-01 until:2022-09-30 exclude:retweets exclude:replies',
              'azuki nft since:2022-04-01 until:2022-06-30 exclude:retweets exclude:replies',
              'azuki nft since:2022-01-01 until:2022-03-31 exclude:retweets exclude:replies'
              ]
          
t_max = 500
t_list = []
for query in azuki_query:
  for i,tweet in enumerate(sntwitter.TwitterSearchScraper(query).get_items()):
          if i>t_max:
              break
          t_list.append([tweet.date, tweet.id, tweet.rawContent, tweet.user.username, tweet.replyCount, tweet.retweetCount ,tweet.likeCount])

azuki_df = pd.DataFrame(t_list, columns=['Datetime', 'Tweet Id', 'Text', 'Username', 'Replies', 'Retweets', 'Likes'])
to_csv(azuki_df, 'azuki_tweets.csv')

azuki_df

,Datetime,Tweet Id,Text,Username,Replies,Retweets,Likes
0,2023-02-13 17:19:58+00:00,1625183011020091393,I'm going LONG &amp; SHORT on blue-chip NFT co...,Irwan0200,0,0,0
1,2023-02-13 17:05:52+00:00,1625179461871181824,Most of the stolen funds came from a single wa...,HiTTrader_co,0,0,0
2,2023-02-13 17:04:06+00:00,1625179015853244417,If you love azuki. i think you love this NFT t...,sheilabrenday11,0,0,0
3,2023-02-13 17:03:44+00:00,1625178923377246208,I'm going LONG &amp; SHORT on blue-chip NFT co...,kanha_7488,0,0,0
4,2023-02-13 16:21:53+00:00,1625168390225788928,Ê∂àÊÅØÔºåÊçÆhttps://t.co/jlm2EtLl9UÊï∞ÊçÆÊòæÁ§∫ÔºåAzukiÁ≥ªÂàóNFTÊÄªÂ∏ÇÂÄºËææ...,ShiLian_Group,0,0,0
...,...,...,...,...,...,...,...
2500,2022-03-29 15:00:00+00:00,1508821280987955200,What does it mean to be a Human Bean?\n\n‚õ©Ô∏è #a...,AzukiBlade,0,0,8
2501,2022-03-29 14:59:56+00:00,1508821262021263367,Great thread. Mentally this is how Ive thought...,Synapsis8835,0,0,1
2502,2022-03-29 14:59:25+00:00,1508821132488716292,#nft sold! üñº ü§ù üí∞\n \nItem number 97...,MetaTradesBot,0,0,0
2503,2022-03-29 14:58:01+00:00,1508820780913762304,‚ÄúShonen Junk is going to flip BAYC and Azuki. ...,asimulacrumisok,4,16,47
2504,2022-03-29 14:56:19+00:00,1508820354084581376,"Azuki 9779 sold for Œû20 ($69,035.89).\n\nhttps...",AzukiSales,0,2,5

### Bored Ape Yacht Club

In [ ]:
bayc_query = ['bored ape yacht club nft since:2023-01-01 until:2023-03-31 exclude:retweets exclude:replies',
              'bored ape yacht club nft since:2022-10-01 until:2022-12-31 exclude:retweets exclude:replies',
              'bored ape yacht club nft since:2022-07-01 until:2022-09-30 exclude:retweets exclude:replies',
              'bored ape yacht club nft since:2022-04-01 until:2022-06-30 exclude:retweets exclude:replies',
              'bored ape yacht club nft since:2022-01-01 until:2022-03-31 exclude:retweets exclude:replies',
              'bored ape yacht club nft since:2021-10-01 until:2021-12-31 exclude:retweets exclude:replies',
              'bored ape yacht club nft since:2021-07-01 until:2021-09-30 exclude:retweets exclude:replies',
              'bored ape yacht club nft since:2021-04-01 until:2021-06-30 exclude:retweets exclude:replies'
              ]
          
t_max = 417
t_list = []
for query in bayc_query:
  for i,tweet in enumerate(sntwitter.TwitterSearchScraper(query).get_items()):
          if i>t_max:
              break
          t_list.append([tweet.date, tweet.id, tweet.rawContent, tweet.user.username, tweet.replyCount, tweet.retweetCount ,tweet.likeCount])

bayc_df = pd.DataFrame(t_list, columns=['Datetime', 'Tweet Id', 'Text', 'Username', 'Replies', 'Retweets', 'Likes'])
to_csv(bayc_df, 'bayc_tweets.csv')

bayc_df

,Datetime,Tweet Id,Text,Username,Replies,Retweets,Likes
0,2023-02-19 17:13:15+00:00,1627355644268257281,Public sale is Live! @cybotz_nftüöÄ\n\nTop 10 #N...,NftsRankingBot,1,0,0
1,2023-02-19 17:12:15+00:00,1627355394560389120,NFT bedrijf achter Bored Ape Yacht Club beschu...,CryptoJournaal,0,0,0
2,2023-02-19 17:04:35+00:00,1627353463968395264,(NFT bedrijf achter Bored Ape Yacht Club besch...,DutchCryptoTalk,0,0,0
3,2023-02-19 17:01:39+00:00,1627352726018424832,NFT bedrijf achter Bored Ape Yacht Club beschu...,bitcoincryptonl,1,0,1
4,2023-02-19 17:00:05+00:00,1627352330730627077,Top 5 trading volumeüí∞ in the past hour\n\nüí∞Vol...,moondataio,0,0,0
...,...,...,...,...,...,...,...
3088,2021-04-23 01:22:23+00:00,1385403645773193222,Getting zen anticipating the Bored Ape Yacht C...,BoredApeYC,4,1,27
3089,2021-04-22 21:08:27+00:00,1385339742036836354,What's THE BATHROOM?\n\nThe Bored Ape Yacht Cl...,BoredApeYC,5,7,33
3090,2021-04-20 00:34:08+00:00,1384304341830410246,"Bored Ape Yacht Club\n\n10,000 programmaticall...",BoredApeYC,18,15,136
3091,2021-04-17 22:07:03+00:00,1383542549407694856,"The Bored Ape Yacht Club is more than just 10,...",BoredApeYC,4,3,19
3092,2021-04-17 04:32:58+00:00,1383277282823872514,"Want to win 1 $ETH?\n\nOur #NFT project, Bored...",GordonGoner,11,3,43

### Meebits

In [ ]:
mee_query = ['meebits nft since:2023-01-01 until:2023-03-31 exclude:retweets exclude:replies',
             'meebits nft since:2022-10-01 until:2022-12-31 exclude:retweets exclude:replies'
             ]
          
t_max = 1250
t_list = []
for query in mee_query:
  for i,tweet in enumerate(sntwitter.TwitterSearchScraper(query).get_items()):
          if i>t_max:
              break
          t_list.append([tweet.date, tweet.id, tweet.rawContent, tweet.user.username, tweet.replyCount, tweet.retweetCount ,tweet.likeCount])

mee_df = pd.DataFrame(t_list, columns=['Datetime', 'Tweet Id', 'Text', 'Username', 'Replies', 'Retweets', 'Likes'])
to_csv(mee_df, 'mee_tweets.csv')

mee_df

,Datetime,Tweet Id,Text,Username,Replies,Retweets,Likes
0,2023-02-13 17:09:25+00:00,1625180355195195393,"Meebit #12900 bought for 3.09 WETH (4,573.57 U...",MeebitsSalesBot,0,0,0
1,2023-02-13 16:33:22+00:00,1625171283255361536,"Meebit #18044 bought for 2.88 ETH (4,245.36 US...",MeebitsSalesBot,0,0,0
2,2023-02-13 16:25:57+00:00,1625169416228065280,"Meebit #3408 bought for 2.90 WETH (4,305.12 US...",MeebitsSalesBot,0,0,1
3,2023-02-13 14:30:08+00:00,1625140267446853645,"Meebit #12957 bought for 4.00 ETH (5,924.68 US...",MeebitsSalesBot,1,0,1
4,2023-02-13 14:01:20+00:00,1625133019974746114,"Meebits Top5 Sales within 24H [ 07:01, Feb 13,...",MeebitsSalesBot,0,0,0
...,...,...,...,...,...,...,...
2497,2022-12-11 21:11:02+00:00,1602048336881647618,#NFT Time! Meebits one day volume is 75.75 $et...,VeryCryptoNerd,0,0,2
2498,2022-12-11 18:38:24+00:00,1602009923348582401,YO DAWG I JUST SAW YOU WASH TRADE THAT @Meebit...,solminingpunk,1,0,3
2499,2022-12-11 15:05:57+00:00,1601956460727975937,"Meebit #14276 bought for 3.56 ETH (4,525.99 US...",MeebitsSalesBot,0,0,0
2500,2022-12-11 14:53:05+00:00,1601953220493946880,"Meebit #19609 bought for 2.85 WETH (3,625.74 U...",MeebitsSalesBot,0,0,0
2501,2022-12-11 14:15:41+00:00,1601943810980057088,"Meebit #18431 bought for 2.61 ETH (3,319.35 US...",MeebitsSalesBot,0,0,0

### CryptoPunks

In [ ]:
punks_query = ['cryptopunks nft since:2023-01-01 until:2023-03-31 exclude:retweets exclude:replies',
              'cryptopunks nft since:2022-10-01 until:2022-12-31 exclude:retweets exclude:replies',
              'cryptopunks nft since:2022-07-01 until:2022-09-30 exclude:retweets exclude:replies',
              'cryptopunks nft since:2022-04-01 until:2022-06-30 exclude:retweets exclude:replies',
              'cryptopunks nft since:2022-01-01 until:2022-03-31 exclude:retweets exclude:replies',
              'cryptopunks nft since:2021-10-01 until:2021-12-31 exclude:retweets exclude:replies',
              'cryptopunks nft since:2021-07-01 until:2021-09-30 exclude:retweets exclude:replies',
              'cryptopunks nft since:2021-04-01 until:2021-06-30 exclude:retweets exclude:replies',
               'cryptopunks nft since:2021-01-01 until:2021-03-31 exclude:retweets exclude:replies',
              ]
          
t_max = 278
t_list = []
for query in punks_query:
  for i,tweet in enumerate(sntwitter.TwitterSearchScraper(query).get_items()):
          if i>t_max:
              break
          t_list.append([tweet.date, tweet.id, tweet.rawContent, tweet.user.username, tweet.replyCount, tweet.retweetCount ,tweet.likeCount])

punks_df = pd.DataFrame(t_list, columns=['Datetime', 'Tweet Id', 'Text', 'Username', 'Replies', 'Retweets', 'Likes'])
to_csv(punks_df, 'punks_tweets.csv')

punks_df

,Datetime,Tweet Id,Text,Username,Replies,Retweets,Likes
0,2023-02-13 17:06:21+00:00,1625179583954788352,How@Chiefs celebrating this morning.Congrats#k...,UKryptopunks,2,0,6
1,2023-02-13 16:55:21+00:00,1625176812308381716,"The Centre Pompidou, home to France's National...",krisbeenft,1,0,1
2,2023-02-13 16:55:00+00:00,1625176724874076161,Mint Now\n\nMint Price : 0.01 ETH\n\nMint Webs...,Trippinapebayc,2,0,6
3,2023-02-13 16:40:17+00:00,1625173020577873924,Many people would argue that cryptopunks marke...,Tinok_eth,1,0,3
4,2023-02-13 16:18:49+00:00,1625167620168097792,France Joins the NFT Revolution as CryptoPunks...,sunisa51795840,0,0,3
...,...,...,...,...,...,...,...
2506,2021-03-29 02:09:51+00:00,1376355897081876483,Cheapest price is 17.75 ETH....I can see #cryp...,BlueHors3Shoe,0,0,1
2507,2021-03-29 01:17:34+00:00,1376342738099175425,Check out my @opensea for season 1 fine art pu...,FinchMuted,0,0,2
2508,2021-03-29 00:49:21+00:00,1376335638442614784,I wonder if avocados aren‚Äôt as popular as I th...,GuaciesNFT,1,0,1
2509,2021-03-29 00:33:38+00:00,1376331682723160066,Look what I just discovered on @opensea! #nft ...,Chaos_Rulezz,0,0,6
2510,2021-03-29 00:32:09+00:00,1376331309212123139,"Just before bedtime, three new males appears o...",DeviantPunks,0,0,6

### CloneX

In [ ]:
clonex_query = ['clonex nft since:2023-01-01 until:2023-03-31 exclude:retweets exclude:replies',
              'clonex nft since:2022-10-01 until:2022-12-31 exclude:retweets exclude:replies',
              'clonex nft since:2022-07-01 until:2022-09-30 exclude:retweets exclude:replies',
              'clonex nft since:2022-04-01 until:2022-06-30 exclude:retweets exclude:replies',
              'clonex nft since:2022-01-01 until:2022-03-31 exclude:retweets exclude:replies'
              ]
          
t_max = 500
t_list = []
for query in clonex_query:
  for i,tweet in enumerate(sntwitter.TwitterSearchScraper(query).get_items()):
          if i>t_max:
              break
          t_list.append([tweet.date, tweet.id, tweet.rawContent, tweet.user.username, tweet.replyCount, tweet.retweetCount ,tweet.likeCount])

clonex_df = pd.DataFrame(t_list, columns=['Datetime', 'Tweet Id', 'Text', 'Username', 'Replies', 'Retweets', 'Likes'])
to_csv(clonex_df, 'clonex_tweets.csv')

clonex_df

,Datetime,Tweet Id,Text,Username,Replies,Retweets,Likes
0,2023-02-13 17:17:12+00:00,1625182314425892865,$9000 made this month from trading NFT not bad...,yasubee0114,0,0,0
1,2023-02-13 17:03:44+00:00,1625178923377246208,I'm going LONG &amp; SHORT on blue-chip NFT co...,kanha_7488,0,0,0
2,2023-02-13 16:31:54+00:00,1625170912411631635,üö® https://t.co/NREXNfxMrC NFT Loan Alert üö® \n\...,ArcadeAlert,0,0,0
3,2023-02-13 16:30:00+00:00,1625170435208888329,"Wow! The NFT collection, RTFKT CloneX by Nike,...",imKeyOfficial,0,0,4
4,2023-02-13 16:18:03+00:00,1625167429382074368,I'm going LONG &amp; SHORT on blue-chip NFT co...,VanillaLatteBoy,0,0,1
...,...,...,...,...,...,...,...
2500,2022-03-24 12:18:39+00:00,1506968736393269248,#nft sold! üñº ü§ù üí∞\n \nItem number 75...,MetaTradesBot,0,0,2
2501,2022-03-24 12:15:36+00:00,1506967966591684616,Bluechip NFT's have officially hit bullmarket ...,FinbrodotETH,9,7,73
2502,2022-03-24 12:15:14+00:00,1506967877026525191,#nft sold! üñº ü§ù üí∞\n \nItem number 80...,MetaTradesBot,0,0,0
2503,2022-03-24 12:03:16+00:00,1506964864564342785,Mayc azuki and clonex kinda crazy \n\nMy bebe ...,NotEasy_NFT,2,0,4
2504,2022-03-24 12:01:49+00:00,1506964499668086784,RTFKT MNLTH quest/challenges ends in March.\n\...,Meta_CloneX,9,13,143

### The Potatoz

In [ ]:
potatoz_query = ['the potatoz nft since:2023-01-01 until:2023-03-31 exclude:retweets exclude:replies',
              'the potatoz nft since:2022-10-01 until:2022-12-31 exclude:retweets exclude:replies',
              'the potatoz nft since:2022-07-01 until:2022-09-30 exclude:retweets exclude:replies'
              ]
          
t_max = 834
t_list = []
for query in potatoz_query:
  for i,tweet in enumerate(sntwitter.TwitterSearchScraper(query).get_items()):
          if i>t_max:
              break
          t_list.append([tweet.date, tweet.id, tweet.rawContent, tweet.user.username, tweet.replyCount, tweet.retweetCount ,tweet.likeCount])

potatoz_df = pd.DataFrame(t_list, columns=['Datetime', 'Tweet Id', 'Text', 'Username', 'Replies', 'Retweets', 'Likes'])
to_csv(potatoz_df, 'potatoz_tweets.csv')

potatoz_df

,Datetime,Tweet Id,Text,Username,Replies,Retweets,Likes
0,2023-02-13 14:00:07+00:00,1625132714591457288,Top 5 trading volumeüí∞ in the past hour\n\nüí∞Vol...,moondataio,0,0,0
1,2023-02-13 07:17:20+00:00,1625031350674751489,i made an ordinal a few days ago of my favouri...,fookedit,0,1,6
2,2023-02-10 00:30:24+00:00,1623841778641272832,"The Potatoz 1692 bought for Œû4.99 ($7,742.78)\...",nftwhalealert,1,1,4
3,2023-02-09 14:03:58+00:00,1623684134764683264,Gm to everyone who‚Äôs willing to crawl over bro...,theNFTshack,0,0,10
4,2023-02-09 07:20:54+00:00,1623582698001387521,NFTs with largest percent change in min sale p...,district_nft,0,1,0
...,...,...,...,...,...,...,...
1295,2022-07-21 15:00:00+00:00,1550133498601775104,1H Top #Nft Sales\n\nThe Potatoz: 1990\nIsekai...,NFTSentimentX,0,2,4
1296,2022-07-21 14:58:40+00:00,1550133160075489282,my math is really bad but I do know the correc...,twomorecoffee,0,0,4
1297,2022-07-21 14:57:58+00:00,1550132984581263366,FOMO Alert: The Potatoz #ThePotatoz\n172 #NFT ...,Promintcc,0,0,2
1298,2022-07-21 14:50:14+00:00,1550131039757996040,Goblintown wtf NFT holders bought\n\n99 pcs T...,nftradersclub,1,5,14
1299,2022-07-21 14:50:02+00:00,1550130989493813249,Top NFT Volume by Sales(in last 10 mins):\nCol...,Nft3T,0,0,0